"""Pydantic request models for the email microservice."""

from __future__ import annotations

from enum import Enum
from typing import Any

from pydantic import BaseModel, EmailStr, Field, model_validator


class EmailType(str, Enum):
    PASSWORD_RESET = "password-reset"  # nosec B105
    ANNOUNCEMENT = "announcement"
    NEW_USER = "new-user"
    ASSIGNMENT = "assignment"
    TEST = "test"


class SendEmailRequest(BaseModel):
    """Unified send request; ``type`` selects the template and validation."""

    type: EmailType
    # Explicit recipients. Omit for announcement to fan out to all users, or
    # for password-reset/new-user when using ``user_emails`` lookups below.
    recipients: list[EmailStr] | None = Field(default=None, max_length=500)
    # Password-reset / new-user: the signed set-password link token produced
    # by src/be/ (this service never issues tokens).
    token: str | None = None
    # Announcement: simple plaintext body delivered to every user.
    body: str | None = None
    # Assignment template fields
    assignment_type: str | None = None
    role: str | None = None
    event_date: str | None = None
    instrument: str | None = None
    notes: str | None = None
    # Overrides for the new-user validity window.
    valid_hours: int | None = Field(default=None, ge=1, le=24 * 14)

    @model_validator(mode="after")
    def validate_per_type(self) -> SendEmailRequest:
        if self.type == EmailType.PASSWORD_RESET:
            if not self.recipients:
                raise ValueError("password-reset requires 'recipients'")
            if not self.token:
                raise ValueError("password-reset requires a 'token' generated by the backend")
        elif self.type == EmailType.NEW_USER:
            if not self.recipients:
                raise ValueError("new-user requires 'recipients'")
            if not self.token:
                raise ValueError("new-user requires a 'token' generated by the backend")
        elif self.type == EmailType.ANNOUNCEMENT:
            if not self.body or not self.body.strip():
                raise ValueError("announcement requires a plaintext 'body'")
        elif self.type == EmailType.ASSIGNMENT:
            if not self.recipients:
                raise ValueError("assignment requires 'recipients'")
            if not (self.assignment_type and self.role and self.event_date):
                raise ValueError("assignment requires 'assignment_type', 'role' and 'event_date'")
        elif self.type == EmailType.TEST:
            if not self.recipients:
                raise ValueError("test requires 'recipients'")
        return self


class SendEmailResponse(BaseModel):
    batch_id: str
    type: EmailType
    sent: int = 0
    failed: int = 0
    recipients: list[str] = Field(default_factory=list)
    failures: list[dict[str, Any]] = Field(default_factory=list)
