"""Add Archived Media table

Revision ID: 380009a5732b
Revises: n3o4p5q6r7s8
Create Date: 2026-06-17 14:54:26.083065

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql
import sqlmodel

# revision identifiers, used by Alembic.
revision: str = '380009a5732b'
down_revision: Union[str, Sequence[str], None] = 'n3o4p5q6r7s8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('archived_media',
    sa.Column("id", sqlmodel.sql.sqltypes.AutoString(length=36), nullable=False),
    sa.Column('created_on', sa.DateTime(), server_default=sa.func.now(), nullable=False),
    sa.Column('updated_on', sa.DateTime(), nullable=True),
    sa.Column('file_location', sqlmodel.sql.sqltypes.AutoString(length=1000), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('archived_media')
    # ### end Alembic commands ###
