"""Generate for Media Tables

Revision ID: 872acb36f3b8
Revises: 91041ee6749a
Create Date: 2026-02-07 11:34:39.724327

"""

from typing import Sequence, Union

from alembic import op  # type: ignore[attr-defined]
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = "872acb36f3b8"
down_revision: Union[str, Sequence[str], None] = "91041ee6749a"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "media",
        sa.Column("id", sqlmodel.sql.sqltypes.AutoString(length=36), nullable=False),
        sa.Column("name", sqlmodel.sql.sqltypes.AutoString(length=200), nullable=False),
        sa.Column("uploaded_on", sa.DateTime(), nullable=False),
        sa.Column("created_on", sa.DateTime(), nullable=False),
        sa.Column("updated_on", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "test",
        sa.Column("id", sqlmodel.sql.sqltypes.AutoString(length=36), nullable=False),
        sa.Column("test1", sa.Integer(), nullable=False),
        sa.Column("test2", sa.Integer(), nullable=False),
        sa.Column("test3", sa.Integer(), nullable=False),
        sa.Column("test4", sa.Integer(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("test")
    op.drop_table("media")
    # ### end Alembic commands ###
