"""Autogenerate migrations from models

Revision ID: 91041ee6749a
Revises: e2412789c190
Create Date: 2026-02-07 11:28:07.195054

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '91041ee6749a'
down_revision: Union[str, Sequence[str], None] = 'e2412789c190'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('item', 'new_id')
    op.drop_index(op.f('new_id'), table_name='user')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('new_id'), 'user', ['new_id'], unique=True)
    op.add_column('item', sa.Column('new_id', mysql.VARCHAR(length=36), nullable=False))
    # ### end Alembic commands ###
