"""Update Video Upload

Revision ID: cf85e3c85d26
Revises: fc2afb5a5fea
Create Date: 2026-04-29 08:28:44.985400

"""

from typing import Sequence, Union

from alembic import op  # type: ignore
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = "cf85e3c85d26"
down_revision: Union[str, Sequence[str], None] = "fc2afb5a5fea"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "videoupload",
        sa.Column("media_association_date", sa.DateTime(), nullable=False),
    )
    op.add_column(
        "videoupload",
        sa.Column("speaker_name", sqlmodel.sql.sqltypes.AutoString(length=200), nullable=True),
    )
    op.add_column(
        "videoupload",
        sa.Column(
            "reference_text",
            sqlmodel.sql.sqltypes.AutoString(length=50),
            nullable=False,
        ),
    )
    op.add_column(
        "videoupload",
        sa.Column("description", sqlmodel.sql.sqltypes.AutoString(length=4000), nullable=False),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("videoupload", "description")
    op.drop_column("videoupload", "reference_text")
    op.drop_column("videoupload", "speaker_name")
    op.drop_column("videoupload", "media_association_date")
    # ### end Alembic commands ###
