import os
import uuid
from pathlib import Path
from typing import Any

from fastapi import APIRouter, File, HTTPException, UploadFile, status
from fastapi.responses import FileResponse

from app.api.deps import SessionDep, require_scope
from app.config import settings
from app.models import Message
from app.repositories.event_repo import EventRepository
from app.requests.event_request import EventBulkDelete, EventCreate, EventUpdate
from app.responses.event_response import EventPublic, EventsPublic

router = APIRouter(prefix="/events", tags=["events"])

# Allowed flyer content types -> file extension
FLYER_CONTENT_TYPES: dict[str, str] = {
    "image/jpeg": ".jpg",
    "image/png": ".png",
    "image/webp": ".webp",
    "image/gif": ".gif",
}

MAX_FLYER_BYTES = 10 * 1024 * 1024


def _flyer_dir() -> Path:
    flyer_dir = Path(settings.EVENT_FLYER_DIR)
    if not flyer_dir.is_absolute():
        # Resolve relative paths against the backend root (src/be), independent of cwd.
        flyer_dir = Path(__file__).resolve().parents[3] / settings.EVENT_FLYER_DIR
    return flyer_dir


def _flyer_public_url(event_id: str) -> str:
    return f"{settings.API_V1_STR}/events/{event_id}/flyer"


def _to_public(event: Any) -> EventPublic:
    return EventPublic(
        id=event.id,
        title=event.title,
        description=event.description,
        date=event.date,
        start_time=event.start_time,
        end_time=event.end_time,
        created_on=event.created_on,
        updated_on=event.updated_on,
        flyer_url=_flyer_public_url(event.id) if event.flyer_path else None,
    )


@router.get("/liveness")
async def get_liveness() -> str:
    """Health check for liveness probe."""
    return "Live"


@router.get("/readiness")
async def get_readiness() -> str:
    """Health check for readiness probe."""
    return "Ready"


@router.get(
    "/",
    response_model=EventsPublic,
)
async def read_events(session: SessionDep, skip: int = 0, limit: int = 100) -> Any:
    """
    Retrieve all event entries.

    Returns a list of all event entries with pagination.
    Public endpoint — used by the public events page.
    """
    repository = EventRepository(session=session)
    events, total_count = await repository.get_all(skip=skip, limit=limit)

    return EventsPublic(data=[_to_public(i) for i in events], count=total_count)


@router.get(
    "/{event_id}",
    response_model=EventPublic,
)
async def read_event_by_id(event_id: str, session: SessionDep) -> Any:
    """
    Get event by ID.

    Returns a single event entry by its ID.
    Public endpoint — used by the public events page.
    """
    repository = EventRepository(session=session)
    event = await repository.get_by_id(event_id=event_id)
    if not event:
        raise HTTPException(
            status_code=status.HTTP_404_NOT_FOUND,
            detail="Event not found",
        )

    return _to_public(event)


@router.get("/{event_id}/flyer")
async def read_event_flyer(event_id: str, session: SessionDep) -> Any:
    """
    Get the flyer image for an event.

    Public endpoint — the public events page and homepage display flyers
    without authentication.
    """
    repository = EventRepository(session=session)
    event = await repository.get_by_id(event_id=event_id)
    if not event or not event.flyer_path:
        raise HTTPException(
            status_code=status.HTTP_404_NOT_FOUND,
            detail="Flyer not found",
        )

    # The stored filename is generated by us (uuid-based); guard anyway against
    # path traversal before joining it to the flyer directory.
    safe_name = os.path.basename(event.flyer_path)
    flyer_file = _flyer_dir() / safe_name
    if not flyer_file.is_file():
        raise HTTPException(
            status_code=status.HTTP_404_NOT_FOUND,
            detail="Flyer not found",
        )

    media_type, _ext = next(
        ((ct, ext) for ct, ext in FLYER_CONTENT_TYPES.items() if safe_name.endswith(ext)),
        ("application/octet-stream", ""),
    )
    return FileResponse(flyer_file, media_type=media_type)


@router.post(
    "/",
    response_model=EventPublic,
    status_code=status.HTTP_201_CREATED,
    dependencies=[require_scope("events:admin")],
)
async def create_event_endpoint(*, session: SessionDep, event_in: EventCreate) -> Any:
    """
    Create new event entry.

    Adds a new event entry to the database.
    """
    repository = EventRepository(session=session)
    event = await repository.create(event_in=event_in)
    return _to_public(event)


@router.post(
    "/{event_id}/flyer",
    response_model=EventPublic,
    dependencies=[require_scope("events:admin")],
)
async def upload_event_flyer_endpoint(
    *,
    session: SessionDep,
    event_id: str,
    file: UploadFile = File(...),
) -> Any:
    """
    Upload (or replace) the flyer image for an event.

    The flyer is displayed on the public events page and, for the next
    upcoming event, on the homepage.
    """
    content_type = file.content_type or ""
    if content_type not in FLYER_CONTENT_TYPES:
        raise HTTPException(
            status_code=status.HTTP_415_UNSUPPORTED_MEDIA_TYPE,
            detail="Flyer must be a JPEG, PNG, WebP, or GIF image",
        )

    payload = await file.read()
    if len(payload) > MAX_FLYER_BYTES:
        raise HTTPException(
            status_code=status.HTTP_413_REQUEST_ENTITY_TOO_LARGE,
            detail="Flyer image exceeds the 10 MB limit",
        )

    repository = EventRepository(session=session)
    event = await repository.get_by_id(event_id=event_id)
    if not event:
        raise HTTPException(
            status_code=status.HTTP_404_NOT_FOUND,
            detail="Event not found",
        )

    flyer_dir = _flyer_dir()
    flyer_dir.mkdir(parents=True, exist_ok=True)

    previous_name = event.flyer_path
    stored_name = f"{event.id}-{uuid.uuid4().hex}{FLYER_CONTENT_TYPES[content_type]}"
    (flyer_dir / stored_name).write_bytes(payload)

    event = await repository.set_flyer(db_event=event, flyer_filename=stored_name)

    # Remove the superseded flyer file best-effort.
    if previous_name:
        try:
            old_file = flyer_dir / os.path.basename(previous_name)
            if old_file.is_file():
                old_file.unlink()
        except OSError:
            pass

    return _to_public(event)


@router.delete(
    "/{event_id}/flyer",
    response_model=Message,
    dependencies=[require_scope("events:admin")],
)
async def delete_event_flyer_endpoint(event_id: str, session: SessionDep) -> Any:
    """
    Remove the flyer image for an event.
    """
    repository = EventRepository(session=session)
    event = await repository.get_by_id(event_id=event_id)
    if not event:
        raise HTTPException(
            status_code=status.HTTP_404_NOT_FOUND,
            detail="Event not found",
        )

    if event.flyer_path:
        flyer_file = _flyer_dir() / os.path.basename(event.flyer_path)
        await repository.set_flyer(db_event=event, flyer_filename=None)
        try:
            if flyer_file.is_file():
                flyer_file.unlink()
        except OSError:
            pass

    return Message(message="Flyer deleted successfully")


@router.patch(
    "/{event_id}",
    response_model=EventPublic,
    dependencies=[require_scope("events:admin")],
)
async def update_event_endpoint(
    *,
    session: SessionDep,
    event_id: str,
    event_in: EventUpdate,
) -> Any:
    """
    Update an event entry.

    Updates an existing event entry by ID.
    """
    repository = EventRepository(session=session)
    event = await repository.get_by_id(event_id=event_id)
    if not event:
        raise HTTPException(
            status_code=status.HTTP_404_NOT_FOUND,
            detail="Event not found",
        )

    event = await repository.update(db_event=event, event_in=event_in)
    return _to_public(event)


def _remove_flyer_file(flyer_path: str | None) -> None:
    """Best-effort removal of a stored flyer file."""
    if not flyer_path:
        return
    try:
        flyer_file = _flyer_dir() / os.path.basename(flyer_path)
        if flyer_file.is_file():
            flyer_file.unlink()
    except OSError:
        pass


@router.delete(
    "/bulk",
    response_model=Message,
    dependencies=[require_scope("events:admin")],
)
async def bulk_delete_events_endpoint(session: SessionDep, bulk_in: EventBulkDelete) -> Any:
    """
    Delete multiple event entries.

    Deletes every event whose id appears in the request body. Ids that do not
    exist are ignored; returns how many events were actually deleted.
    """
    repository = EventRepository(session=session)
    events = await repository.get_many_by_ids(event_ids=list(dict.fromkeys(bulk_in.event_ids)))

    for event in events:
        _remove_flyer_file(event.flyer_path)

    await repository.delete_many(db_events=events)
    return Message(
        message=f"Deleted {len(events)} event{'s' if len(events) != 1 else ''} successfully"
    )


@router.delete(
    "/{event_id}",
    response_model=Message,
    dependencies=[require_scope("events:admin")],
)
async def delete_event_endpoint(event_id: str, session: SessionDep) -> Any:
    """
    Delete an event entry.

    Deletes an event entry by ID.
    """
    repository = EventRepository(session=session)
    event = await repository.get_by_id(event_id=event_id)
    if not event:
        raise HTTPException(
            status_code=status.HTTP_404_NOT_FOUND,
            detail="Event not found",
        )

    _remove_flyer_file(event.flyer_path)

    await repository.delete(db_event=event)
    return Message(message="Event deleted successfully")
