# https://www.kisphp.com/posgresql/docker-compose-setup-for-postgres13-and-pgadmin4
# https://www.pgadmin.org/docs/pgadmin4/latest/container_deployment.html
# https://linuxhint.com/postgresql_docker/
# https://devopsheaven.com/docker/docker-compose/volumes/2018/01/16/volumes-in-docker-compose.html

networks:
  nat:
    external: true

services:
  mariadb:
    image: mariadb:12.1-ubi
    # restart: always
    env_file:
      - ./db.env
    ports:
      - 3306:3306
      - 33060:33060

  adminer:
    image: adminer
    depends_on:
      - mariadb # has to be db because it is configured to look at db
    # restart: always
    ports:
      - 5080:8080