-- This script was generated by the ERD tool in pgAdmin 4.
-- Please log an issue at https://github.com/pgadmin-org/pgadmin4/issues/new/choose if you find any bugs, including reproduction steps.

BEGIN;


CREATE TABLE IF NOT EXISTS public.members
(
    id uuid[] NOT NULL,
    first_name character varying(200)[] NOT NULL,
    last_name character varying(200)[] NOT NULL,
    birthday date,
    wedding_anniversary date,
    baptism_date date,
    PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.sermons
(
    id uuid NOT NULL,
    service_datetime date NOT NULL,
    preacher character varying(200)[],
    sermon_title character varying(200)[],
    edited boolean NOT NULL DEFAULT false,
    uploaded boolean DEFAULT false,
    file_location character varying(1000)[],
    PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.video_uploads
(
    id uuid NOT NULL,
    upload_location character varying(4000)[],
    upload_name character varying(4000)[] NOT NULL,
    PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.announcements
(
    id uuid[],
    sender character varying[] NOT NULL,
    recipients character varying(4000)[] NOT NULL,
    message character varying(8000)[] NOT NULL,
    PRIMARY KEY (id)
);
END;