# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Node.js CI

on:
  push:
    branches: [ $default-branch ]
  pull_request:
    branches: [ $default-branch ]
  workflow_call:


jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [25.x]

    steps:
    - uses: actions/checkout@v5
    - uses: oven-sh/setup-bun@v2
    - name: Restore cached package install
      id: cache-restore
      uses: actions/cache/restore@v4
      with:
        path: |
          ~/.bun/install/cache
        key: ${{ runner.os }}-nextjs-${{ hashFiles('**/bun.lockb') }}-${{ hashFiles('**/*.js', '**/*.jsx', '**/*.ts', '**/*.tsx') }}
    - name: Setup cache configuration
      uses: actions/cache@v4
      id: cache
      with:
        path: |
          ~/.bun/install/cache
        key: ${{ runner.os }}-nextjs-${{ hashFiles('**/bun.lockb') }}-${{ hashFiles('**/*.js', '**/*.jsx', '**/*.ts', '**/*.tsx') }}
        restore-keys: |
          ${{ runner.os }}-nextjs-${{ hashFiles('**/bun.lockb') }}-
    - run: bun install
      # if: steps.cache.outputs.cache-hit != 'true'
      working-directory: src/fe
    - run: bun test:ci
      working-directory: src/fe
    - name: run bun build
      # working-directory: src/fe
      run: |
        cd src/fe
        bun run build
    - name: save files to build dir for .next dir
      # working-directory: src/fe
      run: |
        cd src/fe
        mkdir ${{ github.workspace }}/build
        mkdir ${{ github.workspace }}/build/next
        cp -a .next/. ${{ github.workspace }}/build/next
    - name: save files to build dir
      # working-directory: src/fe
      run: |
        cd src/fe
        mkdir ${{ github.workspace }}/build/out
        cp -a out/. ${{ github.workspace }}/build/out
    - name: Save packages
      id: cache-package-save
      uses: actions/cache/save@v4
      with:
        path: |
          ~/.bun/install/cache
        key: ${{ steps.cache-restore.outputs.cache-primary-key }}
    # - name: Save Build Artifacts
    #   id: cache-artifact-save
    #   uses: actions/cache/save@v4
    #   with:
    #     path: |
    #       src/fe/dist
    #       src/fe/.next
    #     key: ${{ steps.cache-restore.outputs.cache-primary-key }}
    - name: upload-node-artifact
      uses: actions/upload-artifact@v4
      with:
        # Name of the artifact to upload.
        # Optional. Default is 'artifact'
        name: 'afcwebapp'
        path: ${{ github.workspace }}/build
        if-no-files-found: 'error'