# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Node.js CI

on:
  push:
    branches: [ $default-branch ]
  pull_request:
    branches: [ $default-branch ]
  workflow_call:


jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [25.x]

    steps:
    - uses: actions/checkout@v4
    - uses: oven-sh/setup-bun@v2
    - run: bun install
      working-directory: src/fe
    - run: bun test:ci
      working-directory: src/fe
    - run: bun run build
      working-directory: src/fe
    - name: upload-node-artifact
      uses: actions/upload-artifact@v4
      with:
        # Name of the artifact to upload.
        # Optional. Default is 'artifact'
        name: 'afcwebapp'
        path: src/fe/.next
        if-no-files-found: 'error'