name: Pre-commit checks

on:
  push:
    branches: [ main, feature/* ]
  pull_request:
    branches: [ main, feature/* ]
  workflow_dispatch:
  workflow_call:

permissions:
  contents: read

jobs:
  pre-commit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5

      - name: Set up Python
        uses: actions/setup-python@v6
        with:
          python-version: "3.13.5"

      - name: Install pre-commit
        run: pip install pre-commit

      - name: Run pre-commit hooks
        run: pre-commit run --all-files
